// module-federation-demo/app1/src/App.jsx
import React, {Suspense} from "react";
import RemoteApp from 'app2/App';
// const RemoteApp = React.lazy(() => import("app2/App"));

const App = () => {
  return (
    <div>
      <div style={{
        margin:"10px",
        padding:"10px",
        textAlign:"center",
        backgroundColor:"greenyellow"
      }}>
        <h1>App1</h1>
      </div>
      {/* <Suspense fallback={"loading..."}> */}
        <RemoteApp/>
      {/* </Suspense> */}
    </div>)
}

export default App;

// module-federation-demo/v-app1/src/App.vue
<template>
  <div>
    <div :style="{
      margin: '10px',
      padding: '10px',
      textAlign: 'center',
      backgroundColor: 'greenyellow'
    }">
      <h1>App1</h1>
    </div>
    <RemoteApp />
  </div>
</template>

<script setup>
// import { defineAsyncComponent } from 'vue';
import RemoteApp from 'app2/App';

// const RemoteApp = defineAsyncComponent(() => import("app2/App"));
</script>
